### ISSUE TITLE
ubuntu 14.04 repository conflict

### ISSUE THREAD

**Issue by binarytemple** [basho-labs/ansible-riak-common#10]
If this role is run against an ubuntu 14.04 (trusty) image, the 1.4 (apt.basho.com) and 2.x repositories are in conflict (http://packagecloud.io), although packages for trusty are present on packagecloud.

The problem was that the role had added the following line to `/etc/apt/sources.list.d/basho.list`, causing apt to error:

```
deb http://apt.basho.com trusty main
```

I solved the problem by deleting the file `/etc/apt/sources.list.d/basho.list`, and was able to install Riak.

Options for fix would include:
- Detect if installing 1.4 or 2.x, this would require the role to be invoked specifying the Riak version, which adds to complexity, and makes it feel a bit brittle, like so:

```
    - hosts: riak_cluster
      sudo: True
      roles:
      - { role: basho.riak-common, tags: ["riak"], riak_version: 2.0.1}
      }
```
- For the 2.x series of this role, remove the templates which install the 'apt.basho.com' repository.

@jburwell @hectcastro Suggestions welcome.
